### PR TITLE
Isu/035 scripts need to be less fussy over column headings

### PR DESCRIPTION
**Pull request by Joesalmon1985**
Doesn't this need a file called inspect.py?

### CODE REVIEW

**Comment by Ben-green** [comment]
Why do you say that? Do you have a failing test?

**Comment by Joesalmon1985** [comment]
No, I haven't even tried. I realise inspect must be an inbuilt bit of thingy like open and re.

I've tried and I do now have failing tests though

# 

## FAIL: test_makemembersdatawork (t_freshdata.T)

Traceback (most recent call last):
  File "/home/anon/db/Canvas-master/t_freshdata.py", line 340, in test_makemembersdatawork
    self.assertTrue( fd.fColumnInTable( cursor, 'street', 'membersdata' ), "The 'membersdata' TABLE should have a COLUMN 'street'" )
AssertionError: The 'membersdata' TABLE should have a COLUMN 'street'
-------------------- >> begin captured stdout << ---------------------
importmemberdatacsv (  testmemberdata.csv ,  testtoday.db  ): 
testtoday.db
HeadingsFromCSV ( ): Expected a CSV file, got  testtoday.db
importcsvfile ( ): Expected a DB file, got  testmemberdata.csv
importmemberdatacsv ( ): Expected a DB file, got  testmemberdata.csv
No column ' postcode ' got:  [u'Contact Name', u'Joint member name', u'Postal Greeting', u'Email Greeting', u'First Name', u'Last Name', u'Do not mail', u'Addressee', u'Contact ID', u'Membership Type', u'Start Date', u'End Date', u'Member Since', u'Source', u'Status', u'Street Address', u'Supplemental Address 1', u'Supplemental Address 2', u'City', u'Postal Code', u'Country', u'Email', u'Phone (primary)', u'Mobile', u'Ward', u'Local authority', u'Westminster parliament constituency', u'Local party', u'Regional party', u'Override local party']
No column ' street ' got:  [u'Contact Name', u'Joint member name', u'Postal Greeting', u'Email Greeting', u'First Name', u'Last Name', u'Do not mail', u'Addressee', u'Contact ID', u'Membership Type', u'Start Date', u'End Date', u'Member Since', u'Source', u'Status', u'Street Address', u'Supplemental Address 1', u'Supplemental Address 2', u'City', u'Postal Code', u'Country', u'Email', u'Phone (primary)', u'Mobile', u'Ward', u'Local authority', u'Westminster parliament constituency', u'Local party', u'Regional party', u'Override local party']

--------------------- >> end captured stdout << ----------------------

I've also got

# 

## FAIL: test_importolddatacsv (t_freshdata.T)

Traceback (most recent call last):
  File "/home/anon/db/Canvas-master/t_freshdata.py", line 170, in test_importolddatacsv
    self.assertIsNotNone( r )
AssertionError: unexpectedly None
-------------------- >> begin captured stdout << ---------------------
testmeold.csv
Not enough COLUMNs: 25 > 24

--------------------- >> end captured stdout << ----------------------

#

**Comment by Ben-green** [comment]
It is a good idea to put the failing test(s) into an issue. Stand by.

**Comment by Ben-green** [comment]
OK.

May be I was being funny or twee:

Line 164 has

> ```
>     fd.importolddatacsv ( naDataBase, naOldDatacsv  )
> ```

Have you got those the wrong way round. Does importolddatacsv( )
expect the db second?
Should importolddatacsv( ) check and throw an exception if called
wrongly? If so, how dcan it know?

**Pull request merged**
