### PR TITLE
Isu/030 update councilupdate.py

### PR DESCRIPTION
**Pull request by Joesalmon1985**

### CODE REVIEW

**Comment by Ben-green** [comment]
I think that you have not yet pushed the work that we did at lunchtime.

Ben

**Comment by Joesalmon1985** [comment]
Done now, thanks again for your help dude

**Comment by Ben-green** [comment]
> [Shirleys-Yosemite:~/Documents/JOE/Canvas] peterfowler% nosetests-2.7 t_*.py
> 
> # ........FE.
> 
> ## ERROR: test_findcouncildata (t_councilupdate.T)
> 
> Traceback (most recent call last):
>   File "/Users/peterfowler/Documents/JOE/Canvas/t_councilupdate.py", line 34, in test_findcouncildata
>     cu.findcouncildata ( naDataBase )
>   File "/Users/peterfowler/Documents/JOE/Canvas/councilupdate.py", line 144, in findcouncildata
>     importcsvfile.importcsvfile (files,databaseused)
>   File "/Users/peterfowler/Documents/JOE/Canvas/importcsvfile.py", line 28, in importcsvfile
>     HeadingsFromCSV( )
>   File "/Users/peterfowler/Documents/JOE/Canvas/importcsvfile.py", line 117, in HeadingsFromCSV
>     iRowHeadings = iRow
> NameError: global name 'iRow' is not defined
> -------------------- >> begin captured stdout << ---------------------
> creating required tables
> done!
> 
> --------------------- >> end captured stdout << ----------------------
> 
> # 
> 
> ## FAIL: test_createcouncilupdatefiles (t_councilupdate.T)
> 
> Traceback (most recent call last):
>   File "/Users/peterfowler/Documents/JOE/Canvas/t_councilupdate.py", line 28, in test_createcouncilupdatefiles
>     self.assertEqual('notsurehowtest', table1, 'table isnt right or test (It is the test, it would probably work if this had been written in Gvim' )
> AssertionError: table isnt right or test (It is the test, it would probably work if this had been written in Gvim
> -------------------- >> begin captured stdout << ---------------------
> creating required tables
> done!
> (5, u'street', u'TEXT', 0, None, 0)
> 
> --------------------- >> end captured stdout << ----------------------
> 
> ---
> 
> Ran 11 tests in 0.156s
> 
> FAILED (errors=1, failures=1)

So this is looking good?

Ben

**Comment by Joesalmon1985** [comment]
I'm not getting that error when I run t_councilupdate.py myself, although
I'm not running 11 tests either. Have you pushed your new
t_councilupdate.py to git? I can't find it

**Comment by Ben-green** [comment]
OK

I have pushed my latest into ISU/024-importcsvfile_needs_to_handle_apostrophies

**Comment by Ben-green** [comment]
Am I up to date?

**Comment by Joesalmon1985** [comment]
Not only are you up to date, you've fixed that lovely issue. I'm working on
the next bit (Using vim) I'll try to get something up shortly.

A guide to the most useful vim things to do would be awesome, I only use
the search and replace and goto line thing at the moment, any tips welcome

thanks dude!!!!!!!

**Pull request merged**
